name: Website Deploy
 
on:
  push:        
    branches:
      - master

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Installation
      run: yarn
    
    - name: Building Site
      run: yarn build
    
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.4
        tf_actions_subcommand: 'init'
    
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.4
        tf_actions_subcommand: 'plan'
    
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.4
        tf_actions_subcommand: 'apply'

